//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace api.schoolbase.entities.DBSchool
{
    
    public partial class _DBSchool
    {
        public static @__api.schoolbase.entities.DBSchool.Entity.IAM_SchGrade_Columns IAM_SchGrade = new @__api.schoolbase.entities.DBSchool.Entity.IAM_SchGrade_Columns();
    }
    namespace @__api.schoolbase.entities.DBSchool.Entity
    {
        public class IAM_SchGrade_Columns : MyLib.DbAccess.SQL.IQueryTable
        {
            private const string ___TABLE_NAME = "IAM_SchGrade";
            private string ___aliasName;
            public IAM_SchGrade_Columns(string aliasName) : base("DBSchool") { this.___aliasName = aliasName; }
            public IAM_SchGrade_Columns() : base("DBSchool") { this.___aliasName = ___TABLE_NAME; }
    
        #region Table Columns
    
    		private static MyLib.DbAccess.SQL.QueryColumn _GRAID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".GRAID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn GRAID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _GRAID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".GRAID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SpecialtyID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SpecialtyID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn SpecialtyID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SpecialtyID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SpecialtyID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _GradeName = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".GradeName"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn GradeName
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _GradeName;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".GradeName"), DbType.String);
                }
            }

        #endregion

                
            public override string ___GetTableName() { return ___TABLE_NAME; }
    		public override string ___GetAliasName() { return ___aliasName ?? ___TABLE_NAME; }
    				        public override MyLib.DbAccess.SQL.QueryColumn ___GetIdentityColumn() { return _GRAID; }
            		public @__api.schoolbase.entities.DBSchool.Entity.IAM_SchGrade_Columns @__Alias(string aliasName) { return new @__api.schoolbase.entities.DBSchool.Entity.IAM_SchGrade_Columns(aliasName); }
        }
    }
    [System.Serializable]
    public partial class IAM_SchGrade
    {
        #region Property
    
        public virtual long GRAID
        {
            get;
            set;
        }
    
        public virtual long SpecialtyID
        {
            get { return _specialtyID; }
            set
            {
                if (_specialtyID != value)
                {
                    if (IAM_SchSpecialty != null && IAM_SchSpecialty.SERID != value)
                    {
                        IAM_SchSpecialty = null;
                    }
                    _specialtyID = value;
                }
            }
        }
        private long _specialtyID;
    
        public virtual string GradeName
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual IAM_SchSpecialty IAM_SchSpecialty
        {
            get { return _iAM_SchSpecialty; }
            set
            {
                if (!ReferenceEquals(_iAM_SchSpecialty, value))
                {
                    var previousValue = _iAM_SchSpecialty;
                    _iAM_SchSpecialty = value;
                    FixupIAM_SchSpecialty(previousValue);
                }
            }
        }
        private IAM_SchSpecialty _iAM_SchSpecialty;

        #endregion

        #region Association Fixup
    
        private void FixupIAM_SchSpecialty(IAM_SchSpecialty previousValue)
        {
            if (previousValue != null && previousValue.IAM_SchGrade.Contains(this))
            {
                previousValue.IAM_SchGrade.Remove(this);
            }
    
            if (IAM_SchSpecialty != null)
            {
                if (!IAM_SchSpecialty.IAM_SchGrade.Contains(this))
                {
                    IAM_SchSpecialty.IAM_SchGrade.Add(this);
                }
                if (SpecialtyID != IAM_SchSpecialty.SERID)
                {
                    SpecialtyID = IAM_SchSpecialty.SERID;
                }
            }
        }

        #endregion

    }
}
