//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace api.schoolbase.entities.DBSchool
{
    
    public partial class _DBSchool
    {
        public static @__api.schoolbase.entities.DBSchool.Entity.IAM_SchTerm_Columns IAM_SchTerm = new @__api.schoolbase.entities.DBSchool.Entity.IAM_SchTerm_Columns();
    }
    namespace @__api.schoolbase.entities.DBSchool.Entity
    {
        public class IAM_SchTerm_Columns : MyLib.DbAccess.SQL.IQueryTable
        {
            private const string ___TABLE_NAME = "IAM_SchTerm";
            private string ___aliasName;
            public IAM_SchTerm_Columns(string aliasName) : base("DBSchool") { this.___aliasName = aliasName; }
            public IAM_SchTerm_Columns() : base("DBSchool") { this.___aliasName = ___TABLE_NAME; }
    
        #region Table Columns
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SERID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SERID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn SERID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SERID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SERID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SchSerID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SchSerID"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn SchSerID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SchSerID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SchSerID"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SchYear = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SchYear"), DbType.Int32);
            public MyLib.DbAccess.SQL.QueryColumn SchYear
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SchYear;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SchYear"), DbType.Int32);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SchTerm = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SchTerm"), DbType.Byte);
            public MyLib.DbAccess.SQL.QueryColumn SchTerm
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SchTerm;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SchTerm"), DbType.Byte);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StartTime = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StartTime"), DbType.DateTime);
            public MyLib.DbAccess.SQL.QueryColumn StartTime
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StartTime;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StartTime"), DbType.DateTime);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _EndTime = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".EndTime"), DbType.DateTime);
            public MyLib.DbAccess.SQL.QueryColumn EndTime
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _EndTime;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".EndTime"), DbType.DateTime);
                }
            }

        #endregion

                
            public override string ___GetTableName() { return ___TABLE_NAME; }
    		public override string ___GetAliasName() { return ___aliasName ?? ___TABLE_NAME; }
    		        public override IEnumerable<MyLib.DbAccess.SQL.QueryColumn> ___GetAutoIncrementColumn() { return new MyLib.DbAccess.SQL.QueryColumn[]{_SERID}; }
    				        public override MyLib.DbAccess.SQL.QueryColumn ___GetIdentityColumn() { return _SERID; }
            		public @__api.schoolbase.entities.DBSchool.Entity.IAM_SchTerm_Columns @__Alias(string aliasName) { return new @__api.schoolbase.entities.DBSchool.Entity.IAM_SchTerm_Columns(aliasName); }
        }
    }
    [System.Serializable]
    public partial class IAM_SchTerm
    {
        #region Property
    
        public virtual long SERID
        {
            get;
            set;
        }
    
        public virtual string SchSerID
        {
            get;
            set;
        }
    
        public virtual int SchYear
        {
            get;
            set;
        }
    
        public virtual byte SchTerm
        {
            get;
            set;
        }
    
        public virtual System.DateTime StartTime
        {
            get { return _startTime; }
            set { 
    			if (value.Kind == DateTimeKind.Unspecified) {
    			_startTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_startTime = value;
    			}
    			}
        }
        private System.DateTime _startTime;
    
        public virtual System.DateTime EndTime
        {
            get { return _endTime; }
            set { 
    			if (value.Kind == DateTimeKind.Unspecified) {
    			_endTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_endTime = value;
    			}
    			}
        }
        private System.DateTime _endTime;

        #endregion

    }
}
