//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace api.schoolbase.entities.DBSchool
{
    
    public partial class _DBSchool
    {
        public static @__api.schoolbase.entities.DBSchool.Entity.IAM_Student_Columns IAM_Student = new @__api.schoolbase.entities.DBSchool.Entity.IAM_Student_Columns();
    }
    namespace @__api.schoolbase.entities.DBSchool.Entity
    {
        public class IAM_Student_Columns : MyLib.DbAccess.SQL.IQueryTable
        {
            private const string ___TABLE_NAME = "IAM_Student";
            private string ___aliasName;
            public IAM_Student_Columns(string aliasName) : base("DBSchool") { this.___aliasName = aliasName; }
            public IAM_Student_Columns() : base("DBSchool") { this.___aliasName = ___TABLE_NAME; }
    
        #region Table Columns
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuSerID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuSerID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn StuSerID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuSerID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuSerID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuName = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuName"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuName
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuName;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuName"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuSpecialty = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuSpecialty"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn StuSpecialty
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuSpecialty;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuSpecialty"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuIDCard = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuIDCard"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuIDCard
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuIDCard;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuIDCard"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuStatus = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuStatus"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn StuStatus
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuStatus;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuStatus"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuOut = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuOut"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuOut
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuOut;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuOut"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _GraduateDate = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".GraduateDate"), DbType.DateTime);
            public MyLib.DbAccess.SQL.QueryColumn GraduateDate
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _GraduateDate;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".GraduateDate"), DbType.DateTime);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _OriginDate = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".OriginDate"), DbType.DateTime);
            public MyLib.DbAccess.SQL.QueryColumn OriginDate
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _OriginDate;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".OriginDate"), DbType.DateTime);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuID2 = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuID2"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuID2
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuID2;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuID2"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuRegID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuRegID"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuRegID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuRegID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuRegID"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SchStuID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SchStuID"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn SchStuID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SchStuID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SchStuID"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuType = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuType"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuType
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuType;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuType"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuRegNo = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuRegNo"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuRegNo
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuRegNo;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuRegNo"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuBirth = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuBirth"), DbType.DateTime);
            public MyLib.DbAccess.SQL.QueryColumn StuBirth
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuBirth;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuBirth"), DbType.DateTime);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuSex = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuSex"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn StuSex
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuSex;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuSex"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuPolity = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuPolity"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuPolity
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuPolity;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuPolity"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuNation = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuNation"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuNation
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuNation;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuNation"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuOrigin = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuOrigin"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuOrigin
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuOrigin;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuOrigin"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _IsMigrant = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".IsMigrant"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn IsMigrant
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _IsMigrant;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".IsMigrant"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _IsAdult = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".IsAdult"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn IsAdult
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _IsAdult;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".IsAdult"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuResPlz = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuResPlz"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuResPlz
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuResPlz;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuResPlz"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _GraduateSch = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".GraduateSch"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn GraduateSch
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _GraduateSch;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".GraduateSch"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _YuWen = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".YuWen"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn YuWen
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _YuWen;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".YuWen"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _ShuXue = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".ShuXue"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn ShuXue
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _ShuXue;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".ShuXue"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _YingYu = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".YingYu"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn YingYu
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _YingYu;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".YingYu"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _WuLi = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".WuLi"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn WuLi
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _WuLi;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".WuLi"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _HuaXue = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".HuaXue"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn HuaXue
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _HuaXue;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".HuaXue"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _TiYu = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".TiYu"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn TiYu
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _TiYu;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".TiYu"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _TotalScore = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".TotalScore"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn TotalScore
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _TotalScore;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".TotalScore"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuHomePlz = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuHomePlz"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuHomePlz
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuHomePlz;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuHomePlz"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuHomeType = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuHomeType"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuHomeType
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuHomeType;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuHomeType"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _IsGOT = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".IsGOT"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn IsGOT
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _IsGOT;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".IsGOT"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuHomeProvince = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuHomeProvince"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuHomeProvince
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuHomeProvince;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuHomeProvince"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuHomeCity = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuHomeCity"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuHomeCity
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuHomeCity;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuHomeCity"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuHomeArea = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuHomeArea"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuHomeArea
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuHomeArea;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuHomeArea"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuHomeSteet = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuHomeSteet"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuHomeSteet
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuHomeSteet;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuHomeSteet"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuHomeAddr = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuHomeAddr"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuHomeAddr
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuHomeAddr;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuHomeAddr"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuCurrentAddr = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuCurrentAddr"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuCurrentAddr
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuCurrentAddr;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuCurrentAddr"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuZipCode = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuZipCode"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuZipCode
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuZipCode;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuZipCode"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuTel = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuTel"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuTel
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuTel;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuTel"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuPhone = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuPhone"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuPhone
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuPhone;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuPhone"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _FatherName = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".FatherName"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn FatherName
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _FatherName;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".FatherName"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _FatherTel = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".FatherTel"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn FatherTel
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _FatherTel;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".FatherTel"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _FatherComp = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".FatherComp"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn FatherComp
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _FatherComp;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".FatherComp"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _MotherName = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".MotherName"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn MotherName
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _MotherName;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".MotherName"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _MotherTel = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".MotherTel"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn MotherTel
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _MotherTel;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".MotherTel"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _MotherComp = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".MotherComp"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn MotherComp
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _MotherComp;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".MotherComp"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuBZBZ = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuBZBZ"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuBZBZ
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuBZBZ;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuBZBZ"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuPhoto = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuPhoto"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn StuPhoto
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuPhoto;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuPhoto"), DbType.String);
                }
            }

        #endregion

                
            public override string ___GetTableName() { return ___TABLE_NAME; }
    		public override string ___GetAliasName() { return ___aliasName ?? ___TABLE_NAME; }
    				        public override MyLib.DbAccess.SQL.QueryColumn ___GetIdentityColumn() { return _StuSerID; }
            		public @__api.schoolbase.entities.DBSchool.Entity.IAM_Student_Columns @__Alias(string aliasName) { return new @__api.schoolbase.entities.DBSchool.Entity.IAM_Student_Columns(aliasName); }
        }
    }
    [System.Serializable]
    public partial class IAM_Student
    {
        #region Property
    
        public virtual long StuSerID
        {
            get;
            set;
        }
    
        public virtual string StuName
        {
            get;
            set;
        }
    
        public virtual long StuSpecialty
        {
            get;
            set;
        }
    
        public virtual string StuIDCard
        {
            get;
            set;
        }
    
        public virtual long StuStatus
        {
            get;
            set;
        }
    
        public virtual string StuOut
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> GraduateDate
        {
            get { return _graduateDate; }
            set { 
    			if (value != null){
    				if (value.Value.Kind == DateTimeKind.Unspecified) {
    					_graduateDate = DateTime.SpecifyKind(value.Value, DateTimeKind.Utc);
    				} else {
    					_graduateDate = value;
    				}
    			}
    			else 		_graduateDate = value; 
    	}
        }
        private Nullable<System.DateTime> _graduateDate;
    
        public virtual System.DateTime OriginDate
        {
            get { return _originDate; }
            set { 
    			if (value.Kind == DateTimeKind.Unspecified) {
    			_originDate = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_originDate = value;
    			}
    			}
        }
        private System.DateTime _originDate;
    
        public virtual string StuID2
        {
            get;
            set;
        }
    
        public virtual string StuRegID
        {
            get;
            set;
        }
    
        public virtual string SchStuID
        {
            get;
            set;
        }
    
        public virtual string StuType
        {
            get;
            set;
        }
    
        public virtual string StuRegNo
        {
            get;
            set;
        }
    
        public virtual System.DateTime StuBirth
        {
            get { return _stuBirth; }
            set { 
    			if (value.Kind == DateTimeKind.Unspecified) {
    			_stuBirth = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_stuBirth = value;
    			}
    			}
        }
        private System.DateTime _stuBirth;
    
        public virtual long StuSex
        {
            get;
            set;
        }
    
        public virtual string StuPolity
        {
            get;
            set;
        }
    
        public virtual string StuNation
        {
            get;
            set;
        }
    
        public virtual string StuOrigin
        {
            get;
            set;
        }
    
        public virtual string IsMigrant
        {
            get;
            set;
        }
    
        public virtual string IsAdult
        {
            get;
            set;
        }
    
        public virtual string StuResPlz
        {
            get;
            set;
        }
    
        public virtual string GraduateSch
        {
            get;
            set;
        }
    
        public virtual string YuWen
        {
            get;
            set;
        }
    
        public virtual string ShuXue
        {
            get;
            set;
        }
    
        public virtual string YingYu
        {
            get;
            set;
        }
    
        public virtual string WuLi
        {
            get;
            set;
        }
    
        public virtual string HuaXue
        {
            get;
            set;
        }
    
        public virtual string TiYu
        {
            get;
            set;
        }
    
        public virtual string TotalScore
        {
            get;
            set;
        }
    
        public virtual string StuHomePlz
        {
            get;
            set;
        }
    
        public virtual string StuHomeType
        {
            get;
            set;
        }
    
        public virtual string IsGOT
        {
            get;
            set;
        }
    
        public virtual string StuHomeProvince
        {
            get;
            set;
        }
    
        public virtual string StuHomeCity
        {
            get;
            set;
        }
    
        public virtual string StuHomeArea
        {
            get;
            set;
        }
    
        public virtual string StuHomeSteet
        {
            get;
            set;
        }
    
        public virtual string StuHomeAddr
        {
            get;
            set;
        }
    
        public virtual string StuCurrentAddr
        {
            get;
            set;
        }
    
        public virtual string StuZipCode
        {
            get;
            set;
        }
    
        public virtual string StuTel
        {
            get;
            set;
        }
    
        public virtual string StuPhone
        {
            get;
            set;
        }
    
        public virtual string FatherName
        {
            get;
            set;
        }
    
        public virtual string FatherTel
        {
            get;
            set;
        }
    
        public virtual string FatherComp
        {
            get;
            set;
        }
    
        public virtual string MotherName
        {
            get;
            set;
        }
    
        public virtual string MotherTel
        {
            get;
            set;
        }
    
        public virtual string MotherComp
        {
            get;
            set;
        }
    
        public virtual string StuBZBZ
        {
            get;
            set;
        }
    
        public virtual string StuPhoto
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<IAM_StuClass> IAM_StuClass
        {
            get
            {
                if (_iAM_StuClass == null)
                {
                    var newCollection = new MyLib.DAO.FixupCollection<IAM_StuClass>();
                    newCollection.CollectionChanged += FixupIAM_StuClass;
                    _iAM_StuClass = newCollection;
                }
                return _iAM_StuClass;
            }
            set
            {
                if (!ReferenceEquals(_iAM_StuClass, value))
                {
                    var previousValue = _iAM_StuClass as MyLib.DAO.FixupCollection<IAM_StuClass>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupIAM_StuClass;
                    }
                    _iAM_StuClass = value;
                    var newValue = value as MyLib.DAO.FixupCollection<IAM_StuClass>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupIAM_StuClass;
                    }
                }
            }
        }
        private ICollection<IAM_StuClass> _iAM_StuClass;

        #endregion

        #region Association Fixup
    
        private void FixupIAM_StuClass(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (IAM_StuClass item in e.NewItems)
                {
                    item.IAM_Student = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (IAM_StuClass item in e.OldItems)
                {
                    if (ReferenceEquals(item.IAM_Student, this))
                    {
                        item.IAM_Student = null;
                    }
                }
            }
        }

        #endregion

    }
}
