//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace api.schoolbase.entities.DBZiyuan
{
    
    public partial class _DBZiyuan
    {
        public static @__api.schoolbase.entities.DBZiyuan.Entity.ZYK_HistoryView_Columns ZYK_HistoryView = new @__api.schoolbase.entities.DBZiyuan.Entity.ZYK_HistoryView_Columns();
    }
    namespace @__api.schoolbase.entities.DBZiyuan.Entity
    {
        public class ZYK_HistoryView_Columns : MyLib.DbAccess.SQL.IQueryTable
        {
            private const string ___TABLE_NAME = "ZYK_HistoryView";
            private string ___aliasName;
            public ZYK_HistoryView_Columns(string aliasName) : base("DBZiyuan") { this.___aliasName = aliasName; }
            public ZYK_HistoryView_Columns() : base("DBZiyuan") { this.___aliasName = ___TABLE_NAME; }
    
        #region Table Columns
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SERID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SERID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn SERID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SERID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SERID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SchSerID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SchSerID"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn SchSerID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SchSerID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SchSerID"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _UID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".UID"), DbType.Decimal);
            public MyLib.DbAccess.SQL.QueryColumn UID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _UID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".UID"), DbType.Decimal);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _UserType = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".UserType"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn UserType
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _UserType;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".UserType"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _ResID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".ResID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn ResID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _ResID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".ResID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _DTime = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".DTime"), DbType.DateTime);
            public MyLib.DbAccess.SQL.QueryColumn DTime
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _DTime;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".DTime"), DbType.DateTime);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _IP = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".IP"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn IP
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _IP;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".IP"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _ZT = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".ZT"), DbType.Byte);
            public MyLib.DbAccess.SQL.QueryColumn ZT
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _ZT;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".ZT"), DbType.Byte);
                }
            }

        #endregion

                
            public override string ___GetTableName() { return ___TABLE_NAME; }
    		public override string ___GetAliasName() { return ___aliasName ?? ___TABLE_NAME; }
    		        public override IEnumerable<MyLib.DbAccess.SQL.QueryColumn> ___GetAutoIncrementColumn() { return new MyLib.DbAccess.SQL.QueryColumn[]{_SERID}; }
    				        public override MyLib.DbAccess.SQL.QueryColumn ___GetIdentityColumn() { return _SERID; }
            		public @__api.schoolbase.entities.DBZiyuan.Entity.ZYK_HistoryView_Columns @__Alias(string aliasName) { return new @__api.schoolbase.entities.DBZiyuan.Entity.ZYK_HistoryView_Columns(aliasName); }
        }
    }
    [System.Serializable]
    public partial class ZYK_HistoryView
    {
        #region Property
    
        public virtual long SERID
        {
            get;
            set;
        }
    
        public virtual string SchSerID
        {
            get;
            set;
        }
    
        public virtual decimal UID
        {
            get;
            set;
        }
    
        public virtual string UserType
        {
            get;
            set;
        }
    
        public virtual long ResID
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DTime
        {
            get { return _dTime; }
            set { 
    			if (value != null){
    				if (value.Value.Kind == DateTimeKind.Unspecified) {
    					_dTime = DateTime.SpecifyKind(value.Value, DateTimeKind.Utc);
    				} else {
    					_dTime = value;
    				}
    			}
    			else 		_dTime = value; 
    	}
        }
        private Nullable<System.DateTime> _dTime;
    
        public virtual string IP
        {
            get;
            set;
        }
    
        public virtual Nullable<byte> ZT
        {
            get;
            set;
        }

        #endregion

    }
}
