//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace api.schoolbase.entities.DBZiyuan
{
    
    public partial class _DBZiyuan
    {
        public static @__api.schoolbase.entities.DBZiyuan.Entity.ZYK_ResourceCategory_Columns ZYK_ResourceCategory = new @__api.schoolbase.entities.DBZiyuan.Entity.ZYK_ResourceCategory_Columns();
    }
    namespace @__api.schoolbase.entities.DBZiyuan.Entity
    {
        public class ZYK_ResourceCategory_Columns : MyLib.DbAccess.SQL.IQueryTable
        {
            private const string ___TABLE_NAME = "ZYK_ResourceCategory";
            private string ___aliasName;
            public ZYK_ResourceCategory_Columns(string aliasName) : base("DBZiyuan") { this.___aliasName = aliasName; }
            public ZYK_ResourceCategory_Columns() : base("DBZiyuan") { this.___aliasName = ___TABLE_NAME; }
    
        #region Table Columns
    
    		private static MyLib.DbAccess.SQL.QueryColumn _CategoryID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".CategoryID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn CategoryID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _CategoryID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".CategoryID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _ResourceID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".ResourceID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn ResourceID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _ResourceID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".ResourceID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _Switch = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".Switch"), DbType.Boolean);
            public MyLib.DbAccess.SQL.QueryColumn Switch
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _Switch;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".Switch"), DbType.Boolean);
                }
            }

        #endregion

                
            public override string ___GetTableName() { return ___TABLE_NAME; }
    		public override string ___GetAliasName() { return ___aliasName ?? ___TABLE_NAME; }
    				        public override MyLib.DbAccess.SQL.QueryColumn ___GetIdentityColumn() { return _CategoryID; }
            		public @__api.schoolbase.entities.DBZiyuan.Entity.ZYK_ResourceCategory_Columns @__Alias(string aliasName) { return new @__api.schoolbase.entities.DBZiyuan.Entity.ZYK_ResourceCategory_Columns(aliasName); }
        }
    }
    [System.Serializable]
    public partial class ZYK_ResourceCategory
    {
        #region Property
    
        public virtual long CategoryID
        {
            get { return _categoryID; }
            set
            {
                if (_categoryID != value)
                {
                    if (ZYK_SchoolCategory != null && ZYK_SchoolCategory.SERID != value)
                    {
                        ZYK_SchoolCategory = null;
                    }
                    _categoryID = value;
                }
            }
        }
        private long _categoryID;
    
        public virtual long ResourceID
        {
            get { return _resourceID; }
            set
            {
                if (_resourceID != value)
                {
                    if (ZYK_Resource != null && ZYK_Resource.SERID != value)
                    {
                        ZYK_Resource = null;
                    }
                    _resourceID = value;
                }
            }
        }
        private long _resourceID;
    
        public virtual bool Switch
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ZYK_Resource ZYK_Resource
        {
            get { return _zYK_Resource; }
            set
            {
                if (!ReferenceEquals(_zYK_Resource, value))
                {
                    var previousValue = _zYK_Resource;
                    _zYK_Resource = value;
                    FixupZYK_Resource(previousValue);
                }
            }
        }
        private ZYK_Resource _zYK_Resource;
    
        public virtual ZYK_SchoolCategory ZYK_SchoolCategory
        {
            get { return _zYK_SchoolCategory; }
            set
            {
                if (!ReferenceEquals(_zYK_SchoolCategory, value))
                {
                    var previousValue = _zYK_SchoolCategory;
                    _zYK_SchoolCategory = value;
                    FixupZYK_SchoolCategory(previousValue);
                }
            }
        }
        private ZYK_SchoolCategory _zYK_SchoolCategory;

        #endregion

        #region Association Fixup
    
        private void FixupZYK_Resource(ZYK_Resource previousValue)
        {
            if (previousValue != null && previousValue.ZYK_ResourceCategory.Contains(this))
            {
                previousValue.ZYK_ResourceCategory.Remove(this);
            }
    
            if (ZYK_Resource != null)
            {
                if (!ZYK_Resource.ZYK_ResourceCategory.Contains(this))
                {
                    ZYK_Resource.ZYK_ResourceCategory.Add(this);
                }
                if (ResourceID != ZYK_Resource.SERID)
                {
                    ResourceID = ZYK_Resource.SERID;
                }
            }
        }
    
        private void FixupZYK_SchoolCategory(ZYK_SchoolCategory previousValue)
        {
            if (previousValue != null && previousValue.ZYK_ResourceCategory.Contains(this))
            {
                previousValue.ZYK_ResourceCategory.Remove(this);
            }
    
            if (ZYK_SchoolCategory != null)
            {
                if (!ZYK_SchoolCategory.ZYK_ResourceCategory.Contains(this))
                {
                    ZYK_SchoolCategory.ZYK_ResourceCategory.Add(this);
                }
                if (CategoryID != ZYK_SchoolCategory.SERID)
                {
                    CategoryID = ZYK_SchoolCategory.SERID;
                }
            }
        }

        #endregion

    }
}
