//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace api.schoolbase.entities.DBZiyuan
{
    
    public partial class _DBZiyuan
    {
        public static @__api.schoolbase.entities.DBZiyuan.Entity.ZYK_ResourceSection_Columns ZYK_ResourceSection = new @__api.schoolbase.entities.DBZiyuan.Entity.ZYK_ResourceSection_Columns();
    }
    namespace @__api.schoolbase.entities.DBZiyuan.Entity
    {
        public class ZYK_ResourceSection_Columns : MyLib.DbAccess.SQL.IQueryTable
        {
            private const string ___TABLE_NAME = "ZYK_ResourceSection";
            private string ___aliasName;
            public ZYK_ResourceSection_Columns(string aliasName) : base("DBZiyuan") { this.___aliasName = aliasName; }
            public ZYK_ResourceSection_Columns() : base("DBZiyuan") { this.___aliasName = ___TABLE_NAME; }
    
        #region Table Columns
    
    		private static MyLib.DbAccess.SQL.QueryColumn _ResourceID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".ResourceID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn ResourceID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _ResourceID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".ResourceID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SubjectID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SubjectID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn SubjectID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SubjectID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SubjectID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SectionID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SectionID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn SectionID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SectionID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SectionID"), DbType.Int64);
                }
            }

        #endregion

                
            public override string ___GetTableName() { return ___TABLE_NAME; }
    		public override string ___GetAliasName() { return ___aliasName ?? ___TABLE_NAME; }
    				        public override MyLib.DbAccess.SQL.QueryColumn ___GetIdentityColumn() { return _ResourceID; }
            		public @__api.schoolbase.entities.DBZiyuan.Entity.ZYK_ResourceSection_Columns @__Alias(string aliasName) { return new @__api.schoolbase.entities.DBZiyuan.Entity.ZYK_ResourceSection_Columns(aliasName); }
        }
    }
    [System.Serializable]
    public partial class ZYK_ResourceSection
    {
        #region Property
    
        public virtual long ResourceID
        {
            get { return _resourceID; }
            set
            {
                if (_resourceID != value)
                {
                    if (ZYK_Resource != null && ZYK_Resource.SERID != value)
                    {
                        ZYK_Resource = null;
                    }
                    _resourceID = value;
                }
            }
        }
        private long _resourceID;
    
        public virtual long SubjectID
        {
            get;
            set;
        }
    
        public virtual long SectionID
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ZYK_Resource ZYK_Resource
        {
            get { return _zYK_Resource; }
            set
            {
                if (!ReferenceEquals(_zYK_Resource, value))
                {
                    var previousValue = _zYK_Resource;
                    _zYK_Resource = value;
                    FixupZYK_Resource(previousValue);
                }
            }
        }
        private ZYK_Resource _zYK_Resource;

        #endregion

        #region Association Fixup
    
        private void FixupZYK_Resource(ZYK_Resource previousValue)
        {
            if (previousValue != null && previousValue.ZYK_ResourceSection.Contains(this))
            {
                previousValue.ZYK_ResourceSection.Remove(this);
            }
    
            if (ZYK_Resource != null)
            {
                if (!ZYK_Resource.ZYK_ResourceSection.Contains(this))
                {
                    ZYK_Resource.ZYK_ResourceSection.Add(this);
                }
                if (ResourceID != ZYK_Resource.SERID)
                {
                    ResourceID = ZYK_Resource.SERID;
                }
            }
        }

        #endregion

    }
}
