//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace api.schoolbase.entities.DBZiyuan
{
    
    public partial class _DBZiyuan
    {
        public static @__api.schoolbase.entities.DBZiyuan.Entity.ZYK_ResourceFavorite_Columns ZYK_ResourceFavorite = new @__api.schoolbase.entities.DBZiyuan.Entity.ZYK_ResourceFavorite_Columns();
    }
    namespace @__api.schoolbase.entities.DBZiyuan.Entity
    {
        public class ZYK_ResourceFavorite_Columns : MyLib.DbAccess.SQL.IQueryTable
        {
            private const string ___TABLE_NAME = "ZYK_ResourceFavorite";
            private string ___aliasName;
            public ZYK_ResourceFavorite_Columns(string aliasName) : base("DBZiyuan") { this.___aliasName = aliasName; }
            public ZYK_ResourceFavorite_Columns() : base("DBZiyuan") { this.___aliasName = ___TABLE_NAME; }
    
        #region Table Columns
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SERID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SERID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn SERID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SERID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SERID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _ResID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".ResID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn ResID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _ResID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".ResID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _FClasID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".FClasID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn FClasID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _FClasID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".FClasID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _UID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".UID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn UID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _UID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".UID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _Dtime = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".Dtime"), DbType.DateTime);
            public MyLib.DbAccess.SQL.QueryColumn Dtime
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _Dtime;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".Dtime"), DbType.DateTime);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _Attention = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".Attention"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn Attention
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _Attention;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".Attention"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _ZT = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".ZT"), DbType.Byte);
            public MyLib.DbAccess.SQL.QueryColumn ZT
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _ZT;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".ZT"), DbType.Byte);
                }
            }

        #endregion

                
            public override string ___GetTableName() { return ___TABLE_NAME; }
    		public override string ___GetAliasName() { return ___aliasName ?? ___TABLE_NAME; }
    		        public override IEnumerable<MyLib.DbAccess.SQL.QueryColumn> ___GetAutoIncrementColumn() { return new MyLib.DbAccess.SQL.QueryColumn[]{_SERID}; }
    				        public override MyLib.DbAccess.SQL.QueryColumn ___GetIdentityColumn() { return _SERID; }
            		public @__api.schoolbase.entities.DBZiyuan.Entity.ZYK_ResourceFavorite_Columns @__Alias(string aliasName) { return new @__api.schoolbase.entities.DBZiyuan.Entity.ZYK_ResourceFavorite_Columns(aliasName); }
        }
    }
    [System.Serializable]
    public partial class ZYK_ResourceFavorite
    {
        #region Property
    
        public virtual long SERID
        {
            get;
            set;
        }
    
        public virtual long ResID
        {
            get;
            set;
        }
    
        public virtual long FClasID
        {
            get;
            set;
        }
    
        public virtual long UID
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Dtime
        {
            get { return _dtime; }
            set { 
    			if (value != null){
    				if (value.Value.Kind == DateTimeKind.Unspecified) {
    					_dtime = DateTime.SpecifyKind(value.Value, DateTimeKind.Utc);
    				} else {
    					_dtime = value;
    				}
    			}
    			else 		_dtime = value; 
    	}
        }
        private Nullable<System.DateTime> _dtime;
    
        public virtual string Attention
        {
            get;
            set;
        }
    
        public virtual byte ZT
        {
            get;
            set;
        }

        #endregion

    }
}
