//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace api.schoolbase.entities.DBSyllabus
{
    
    public partial class _DBSyllabus
    {
        public static @__api.schoolbase.entities.DBSyllabus.Entity.area_Columns area = new @__api.schoolbase.entities.DBSyllabus.Entity.area_Columns();
    }
    namespace @__api.schoolbase.entities.DBSyllabus.Entity
    {
        public class area_Columns : MyLib.DbAccess.SQL.IQueryTable
        {
            private const string ___TABLE_NAME = "area";
            private string ___aliasName;
            public area_Columns(string aliasName) : base("DBSyllabus") { this.___aliasName = aliasName; }
            public area_Columns() : base("DBSyllabus") { this.___aliasName = ___TABLE_NAME; }
    
        #region Table Columns
    
    		private static MyLib.DbAccess.SQL.QueryColumn _id = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".id"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn id
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _id;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".id"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _areaname = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".areaname"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn areaname
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _areaname;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".areaname"), DbType.String);
                }
            }

        #endregion

                
            public override string ___GetTableName() { return ___TABLE_NAME; }
    		public override string ___GetAliasName() { return ___aliasName ?? ___TABLE_NAME; }
    				        public override MyLib.DbAccess.SQL.QueryColumn ___GetIdentityColumn() { return _id; }
            		public @__api.schoolbase.entities.DBSyllabus.Entity.area_Columns @__Alias(string aliasName) { return new @__api.schoolbase.entities.DBSyllabus.Entity.area_Columns(aliasName); }
        }
    }
    [System.Serializable]
    public partial class area
    {
        #region Property
    
        public virtual string id
        {
            get;
            set;
        }
    
        public virtual string areaname
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<syllabus> syllabus
        {
            get
            {
                if (_syllabus == null)
                {
                    var newCollection = new MyLib.DAO.FixupCollection<syllabus>();
                    newCollection.CollectionChanged += Fixupsyllabus;
                    _syllabus = newCollection;
                }
                return _syllabus;
            }
            set
            {
                if (!ReferenceEquals(_syllabus, value))
                {
                    var previousValue = _syllabus as MyLib.DAO.FixupCollection<syllabus>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupsyllabus;
                    }
                    _syllabus = value;
                    var newValue = value as MyLib.DAO.FixupCollection<syllabus>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupsyllabus;
                    }
                }
            }
        }
        private ICollection<syllabus> _syllabus;

        #endregion

        #region Association Fixup
    
        private void Fixupsyllabus(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (syllabus item in e.NewItems)
                {
                    item.area1 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (syllabus item in e.OldItems)
                {
                    if (ReferenceEquals(item.area1, this))
                    {
                        item.area1 = null;
                    }
                }
            }
        }

        #endregion

    }
}
