//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace api.schoolbase.entities.DBSyllabus
{
    
    public partial class _DBSyllabus
    {
        public static @__api.schoolbase.entities.DBSyllabus.Entity.vsections_Columns vsections = new @__api.schoolbase.entities.DBSyllabus.Entity.vsections_Columns();
    }
    namespace @__api.schoolbase.entities.DBSyllabus.Entity
    {
        public class vsections_Columns : MyLib.DbAccess.SQL.IQueryTable
        {
            private const string ___TABLE_NAME = "vsections";
            private string ___aliasName;
            public vsections_Columns(string aliasName) : base("DBSyllabus") { this.___aliasName = aliasName; }
            public vsections_Columns() : base("DBSyllabus") { this.___aliasName = ___TABLE_NAME; }
    
        #region Table Columns
    
    		private static MyLib.DbAccess.SQL.QueryColumn _subjectid = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".subjectid"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn subjectid
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _subjectid;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".subjectid"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _subjectname = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".subjectname"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn subjectname
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _subjectname;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".subjectname"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _chapterid = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".chapterid"), DbType.Int32);
            public MyLib.DbAccess.SQL.QueryColumn chapterid
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _chapterid;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".chapterid"), DbType.Int32);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _chapter = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".chapter"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn chapter
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _chapter;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".chapter"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _sectionid = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".sectionid"), DbType.Int32);
            public MyLib.DbAccess.SQL.QueryColumn sectionid
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _sectionid;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".sectionid"), DbType.Int32);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _section = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".section"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn section
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _section;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".section"), DbType.String);
                }
            }

        #endregion

                
            public override string ___GetTableName() { return ___TABLE_NAME; }
    		public override string ___GetAliasName() { return ___aliasName ?? ___TABLE_NAME; }
    				        public override MyLib.DbAccess.SQL.QueryColumn ___GetIdentityColumn() { return _subjectid; }
            		public @__api.schoolbase.entities.DBSyllabus.Entity.vsections_Columns @__Alias(string aliasName) { return new @__api.schoolbase.entities.DBSyllabus.Entity.vsections_Columns(aliasName); }
        }
    }
    [System.Serializable]
    public partial class vsections
    {
        #region Property
    
        public virtual long subjectid
        {
            get;
            set;
        }
    
        public virtual string subjectname
        {
            get;
            set;
        }
    
        public virtual int chapterid
        {
            get;
            set;
        }
    
        public virtual string chapter
        {
            get;
            set;
        }
    
        public virtual int sectionid
        {
            get;
            set;
        }
    
        public virtual string section
        {
            get;
            set;
        }

        #endregion

    }
}
