//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace api.schoolbase.entities.DBSyllabus
{
    
    public partial class _DBSyllabus
    {
        public static @__api.schoolbase.entities.DBSyllabus.Entity.vsyllabussections_Columns vsyllabussections = new @__api.schoolbase.entities.DBSyllabus.Entity.vsyllabussections_Columns();
    }
    namespace @__api.schoolbase.entities.DBSyllabus.Entity
    {
        public class vsyllabussections_Columns : MyLib.DbAccess.SQL.IQueryTable
        {
            private const string ___TABLE_NAME = "vsyllabussections";
            private string ___aliasName;
            public vsyllabussections_Columns(string aliasName) : base("DBSyllabus") { this.___aliasName = aliasName; }
            public vsyllabussections_Columns() : base("DBSyllabus") { this.___aliasName = ___TABLE_NAME; }
    
        #region Table Columns
    
    		private static MyLib.DbAccess.SQL.QueryColumn _syllabusid = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".syllabusid"), DbType.Int32);
            public MyLib.DbAccess.SQL.QueryColumn syllabusid
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _syllabusid;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".syllabusid"), DbType.Int32);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _syllabusname = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".syllabusname"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn syllabusname
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _syllabusname;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".syllabusname"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _subjectid = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".subjectid"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn subjectid
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _subjectid;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".subjectid"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _gradeid = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".gradeid"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn gradeid
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _gradeid;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".gradeid"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _chapterid = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".chapterid"), DbType.Int16);
            public MyLib.DbAccess.SQL.QueryColumn chapterid
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _chapterid;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".chapterid"), DbType.Int16);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _chapter = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".chapter"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn chapter
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _chapter;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".chapter"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _chapter_prefix = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".chapter_prefix"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn chapter_prefix
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _chapter_prefix;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".chapter_prefix"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _term = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".term"), DbType.Int16);
            public MyLib.DbAccess.SQL.QueryColumn term
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _term;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".term"), DbType.Int16);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _sectionid = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".sectionid"), DbType.Int32);
            public MyLib.DbAccess.SQL.QueryColumn sectionid
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _sectionid;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".sectionid"), DbType.Int32);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _section_prefix = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".section_prefix"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn section_prefix
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _section_prefix;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".section_prefix"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _sectiontext = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".sectiontext"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn sectiontext
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _sectiontext;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".sectiontext"), DbType.String);
                }
            }

        #endregion

                
            public override string ___GetTableName() { return ___TABLE_NAME; }
    		public override string ___GetAliasName() { return ___aliasName ?? ___TABLE_NAME; }
    				        public override MyLib.DbAccess.SQL.QueryColumn ___GetIdentityColumn() { return _syllabusid; }
            		public @__api.schoolbase.entities.DBSyllabus.Entity.vsyllabussections_Columns @__Alias(string aliasName) { return new @__api.schoolbase.entities.DBSyllabus.Entity.vsyllabussections_Columns(aliasName); }
        }
    }
    [System.Serializable]
    public partial class vsyllabussections
    {
        #region Property
    
        public virtual int syllabusid
        {
            get;
            set;
        }
    
        public virtual string syllabusname
        {
            get;
            set;
        }
    
        public virtual long subjectid
        {
            get;
            set;
        }
    
        public virtual long gradeid
        {
            get;
            set;
        }
    
        public virtual short chapterid
        {
            get;
            set;
        }
    
        public virtual string chapter
        {
            get;
            set;
        }
    
        public virtual string chapter_prefix
        {
            get;
            set;
        }
    
        public virtual short term
        {
            get;
            set;
        }
    
        public virtual int sectionid
        {
            get;
            set;
        }
    
        public virtual string section_prefix
        {
            get;
            set;
        }
    
        public virtual string sectiontext
        {
            get;
            set;
        }

        #endregion

    }
}
