//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace api.schoolbase.entities.DBSchoolCourse
{
    
    public partial class _DBSchoolCourse
    {
        public static @__api.schoolbase.entities.DBSchoolCourse.Entity.IAM_StuSelectedCourse_Columns IAM_StuSelectedCourse = new @__api.schoolbase.entities.DBSchoolCourse.Entity.IAM_StuSelectedCourse_Columns();
    }
    namespace @__api.schoolbase.entities.DBSchoolCourse.Entity
    {
        public class IAM_StuSelectedCourse_Columns : MyLib.DbAccess.SQL.IQueryTable
        {
            private const string ___TABLE_NAME = "IAM_StuSelectedCourse";
            private string ___aliasName;
            public IAM_StuSelectedCourse_Columns(string aliasName) : base("DBSchoolCourse") { this.___aliasName = aliasName; }
            public IAM_StuSelectedCourse_Columns() : base("DBSchoolCourse") { this.___aliasName = ___TABLE_NAME; }
    
        #region Table Columns
    
    		private static MyLib.DbAccess.SQL.QueryColumn _CourseSerID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".CourseSerID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn CourseSerID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _CourseSerID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".CourseSerID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _StuSerID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".StuSerID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn StuSerID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _StuSerID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".StuSerID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _isRequired = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".isRequired"), DbType.Boolean);
            public MyLib.DbAccess.SQL.QueryColumn isRequired
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _isRequired;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".isRequired"), DbType.Boolean);
                }
            }

        #endregion

                
            public override string ___GetTableName() { return ___TABLE_NAME; }
    		public override string ___GetAliasName() { return ___aliasName ?? ___TABLE_NAME; }
    				        public override MyLib.DbAccess.SQL.QueryColumn ___GetIdentityColumn() { return _CourseSerID; }
            		public @__api.schoolbase.entities.DBSchoolCourse.Entity.IAM_StuSelectedCourse_Columns @__Alias(string aliasName) { return new @__api.schoolbase.entities.DBSchoolCourse.Entity.IAM_StuSelectedCourse_Columns(aliasName); }
        }
    }
    [System.Serializable]
    public partial class IAM_StuSelectedCourse
    {
        #region Property
    
        public virtual long CourseSerID
        {
            get { return _courseSerID; }
            set
            {
                if (_courseSerID != value)
                {
                    if (IAM_TeaCourse != null && IAM_TeaCourse.SerID != value)
                    {
                        IAM_TeaCourse = null;
                    }
                    _courseSerID = value;
                }
            }
        }
        private long _courseSerID;
    
        public virtual long StuSerID
        {
            get;
            set;
        }
    
        public virtual bool isRequired
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual IAM_TeaCourse IAM_TeaCourse
        {
            get { return _iAM_TeaCourse; }
            set
            {
                if (!ReferenceEquals(_iAM_TeaCourse, value))
                {
                    var previousValue = _iAM_TeaCourse;
                    _iAM_TeaCourse = value;
                    FixupIAM_TeaCourse(previousValue);
                }
            }
        }
        private IAM_TeaCourse _iAM_TeaCourse;

        #endregion

        #region Association Fixup
    
        private void FixupIAM_TeaCourse(IAM_TeaCourse previousValue)
        {
            if (previousValue != null && previousValue.IAM_StuSelectedCourse.Contains(this))
            {
                previousValue.IAM_StuSelectedCourse.Remove(this);
            }
    
            if (IAM_TeaCourse != null)
            {
                if (!IAM_TeaCourse.IAM_StuSelectedCourse.Contains(this))
                {
                    IAM_TeaCourse.IAM_StuSelectedCourse.Add(this);
                }
                if (CourseSerID != IAM_TeaCourse.SerID)
                {
                    CourseSerID = IAM_TeaCourse.SerID;
                }
            }
        }

        #endregion

    }
}
