//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace api.schoolbase.entities.DBSchoolCourse
{
    
    public partial class _DBSchoolCourse
    {
        public static @__api.schoolbase.entities.DBSchoolCourse.Entity.VClassTeacher_Columns VClassTeacher = new @__api.schoolbase.entities.DBSchoolCourse.Entity.VClassTeacher_Columns();
    }
    namespace @__api.schoolbase.entities.DBSchoolCourse.Entity
    {
        public class VClassTeacher_Columns : MyLib.DbAccess.SQL.IQueryTable
        {
            private const string ___TABLE_NAME = "VClassTeacher";
            private string ___aliasName;
            public VClassTeacher_Columns(string aliasName) : base("DBSchoolCourse") { this.___aliasName = aliasName; }
            public VClassTeacher_Columns() : base("DBSchoolCourse") { this.___aliasName = ___TABLE_NAME; }
    
        #region Table Columns
    
    		private static MyLib.DbAccess.SQL.QueryColumn _ClassSerID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".ClassSerID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn ClassSerID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _ClassSerID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".ClassSerID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _ClassName = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".ClassName"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn ClassName
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _ClassName;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".ClassName"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SpecialtyNameOfClass = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SpecialtyNameOfClass"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn SpecialtyNameOfClass
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SpecialtyNameOfClass;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SpecialtyNameOfClass"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SpecialtyIDOfClass = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SpecialtyIDOfClass"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn SpecialtyIDOfClass
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SpecialtyIDOfClass;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SpecialtyIDOfClass"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SPEIDOfClass = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SPEIDOfClass"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn SPEIDOfClass
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SPEIDOfClass;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SPEIDOfClass"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _TeaSerID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".TeaSerID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn TeaSerID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _TeaSerID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".TeaSerID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _TeaName = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".TeaName"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn TeaName
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _TeaName;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".TeaName"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _TeaPhoto = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".TeaPhoto"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn TeaPhoto
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _TeaPhoto;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".TeaPhoto"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SchSerID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SchSerID"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn SchSerID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SchSerID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SchSerID"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SpecialtyIDOfSubject = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SpecialtyIDOfSubject"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn SpecialtyIDOfSubject
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SpecialtyIDOfSubject;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SpecialtyIDOfSubject"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SPEIDOfSubject = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SPEIDOfSubject"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn SPEIDOfSubject
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SPEIDOfSubject;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SPEIDOfSubject"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SpecNameOfSubject = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SpecNameOfSubject"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn SpecNameOfSubject
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SpecNameOfSubject;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SpecNameOfSubject"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _GRAID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".GRAID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn GRAID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _GRAID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".GRAID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _GradeName = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".GradeName"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn GradeName
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _GradeName;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".GradeName"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _LoopType = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".LoopType"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn LoopType
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _LoopType;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".LoopType"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _RequiredTime = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".RequiredTime"), DbType.Int32);
            public MyLib.DbAccess.SQL.QueryColumn RequiredTime
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _RequiredTime;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".RequiredTime"), DbType.Int32);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _DTime = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".DTime"), DbType.DateTime);
            public MyLib.DbAccess.SQL.QueryColumn DTime
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _DTime;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".DTime"), DbType.DateTime);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _Switch = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".Switch"), DbType.Boolean);
            public MyLib.DbAccess.SQL.QueryColumn Switch
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _Switch;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".Switch"), DbType.Boolean);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _Score = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".Score"), DbType.Int32);
            public MyLib.DbAccess.SQL.QueryColumn Score
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _Score;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".Score"), DbType.Int32);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _CourseSerID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".CourseSerID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn CourseSerID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _CourseSerID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".CourseSerID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _Status = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".Status"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn Status
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _Status;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".Status"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SubjectID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SubjectID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn SubjectID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SubjectID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SubjectID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SubjectName = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SubjectName"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn SubjectName
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SubjectName;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SubjectName"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SchYear = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SchYear"), DbType.Int32);
            public MyLib.DbAccess.SQL.QueryColumn SchYear
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SchYear;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SchYear"), DbType.Int32);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SchTerm = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SchTerm"), DbType.Byte);
            public MyLib.DbAccess.SQL.QueryColumn SchTerm
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SchTerm;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SchTerm"), DbType.Byte);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _IsMust = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".IsMust"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn IsMust
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _IsMust;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".IsMust"), DbType.Int64);
                }
            }

        #endregion

                
            public override string ___GetTableName() { return ___TABLE_NAME; }
    		public override string ___GetAliasName() { return ___aliasName ?? ___TABLE_NAME; }
    				        public override MyLib.DbAccess.SQL.QueryColumn ___GetIdentityColumn() { return _ClassSerID; }
            		public @__api.schoolbase.entities.DBSchoolCourse.Entity.VClassTeacher_Columns @__Alias(string aliasName) { return new @__api.schoolbase.entities.DBSchoolCourse.Entity.VClassTeacher_Columns(aliasName); }
        }
    }
    [System.Serializable]
    public partial class VClassTeacher
    {
        #region Property
    
        public virtual long ClassSerID
        {
            get;
            set;
        }
    
        public virtual string ClassName
        {
            get;
            set;
        }
    
        public virtual string SpecialtyNameOfClass
        {
            get;
            set;
        }
    
        public virtual long SpecialtyIDOfClass
        {
            get;
            set;
        }
    
        public virtual long SPEIDOfClass
        {
            get;
            set;
        }
    
        public virtual long TeaSerID
        {
            get;
            set;
        }
    
        public virtual string TeaName
        {
            get;
            set;
        }
    
        public virtual string TeaPhoto
        {
            get;
            set;
        }
    
        public virtual string SchSerID
        {
            get;
            set;
        }
    
        public virtual long SpecialtyIDOfSubject
        {
            get;
            set;
        }
    
        public virtual long SPEIDOfSubject
        {
            get;
            set;
        }
    
        public virtual string SpecNameOfSubject
        {
            get;
            set;
        }
    
        public virtual long GRAID
        {
            get;
            set;
        }
    
        public virtual string GradeName
        {
            get;
            set;
        }
    
        public virtual long LoopType
        {
            get;
            set;
        }
    
        public virtual int RequiredTime
        {
            get;
            set;
        }
    
        public virtual System.DateTime DTime
        {
            get { return _dTime; }
            set { 
    			if (value.Kind == DateTimeKind.Unspecified) {
    			_dTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_dTime = value;
    			}
    			}
        }
        private System.DateTime _dTime;
    
        public virtual bool Switch
        {
            get;
            set;
        }
    
        public virtual int Score
        {
            get;
            set;
        }
    
        public virtual long CourseSerID
        {
            get;
            set;
        }
    
        public virtual long Status
        {
            get;
            set;
        }
    
        public virtual long SubjectID
        {
            get;
            set;
        }
    
        public virtual string SubjectName
        {
            get;
            set;
        }
    
        public virtual int SchYear
        {
            get;
            set;
        }
    
        public virtual byte SchTerm
        {
            get;
            set;
        }
    
        public virtual long IsMust
        {
            get;
            set;
        }

        #endregion

    }
}
