//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace api.schoolbase.entities.DBBase
{
    
    public partial class _DBBase
    {
        public static @__api.schoolbase.entities.DBBase.Entity.Base_Admin_Columns Base_Admin = new @__api.schoolbase.entities.DBBase.Entity.Base_Admin_Columns();
    }
    namespace @__api.schoolbase.entities.DBBase.Entity
    {
        public class Base_Admin_Columns : MyLib.DbAccess.SQL.IQueryTable
        {
            private const string ___TABLE_NAME = "Base_Admin";
            private string ___aliasName;
            public Base_Admin_Columns(string aliasName) : base("DBBase") { this.___aliasName = aliasName; }
            public Base_Admin_Columns() : base("DBBase") { this.___aliasName = ___TABLE_NAME; }
    
        #region Table Columns
    
    		private static MyLib.DbAccess.SQL.QueryColumn _UID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".UID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn UID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _UID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".UID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _UserName = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".UserName"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn UserName
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _UserName;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".UserName"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _Tel = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".Tel"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn Tel
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _Tel;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".Tel"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _Email = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".Email"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn Email
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _Email;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".Email"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _Addr = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".Addr"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn Addr
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _Addr;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".Addr"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _DTime = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".DTime"), DbType.DateTime);
            public MyLib.DbAccess.SQL.QueryColumn DTime
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _DTime;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".DTime"), DbType.DateTime);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _IP = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".IP"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn IP
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _IP;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".IP"), DbType.String);
                }
            }

        #endregion

                
            public override string ___GetTableName() { return ___TABLE_NAME; }
    		public override string ___GetAliasName() { return ___aliasName ?? ___TABLE_NAME; }
    				        public override MyLib.DbAccess.SQL.QueryColumn ___GetIdentityColumn() { return _UID; }
            		public @__api.schoolbase.entities.DBBase.Entity.Base_Admin_Columns @__Alias(string aliasName) { return new @__api.schoolbase.entities.DBBase.Entity.Base_Admin_Columns(aliasName); }
        }
    }
    [System.Serializable]
    public partial class Base_Admin
    {
        #region Property
    
        public virtual long UID
        {
            get { return _uID; }
            set
            {
                if (_uID != value)
                {
                    if (tUser_ex != null && tUser_ex.UID != value)
                    {
                        tUser_ex = null;
                    }
                    _uID = value;
                }
            }
        }
        private long _uID;
    
        public virtual string UserName
        {
            get;
            set;
        }
    
        public virtual string Tel
        {
            get;
            set;
        }
    
        public virtual string Email
        {
            get;
            set;
        }
    
        public virtual string Addr
        {
            get;
            set;
        }
    
        public virtual System.DateTime DTime
        {
            get { return _dTime; }
            set { 
    			if (value.Kind == DateTimeKind.Unspecified) {
    			_dTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_dTime = value;
    			}
    			}
        }
        private System.DateTime _dTime;
    
        public virtual string IP
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual tUser_ex tUser_ex
        {
            get { return _tUser_ex; }
            set
            {
                if (!ReferenceEquals(_tUser_ex, value))
                {
                    var previousValue = _tUser_ex;
                    _tUser_ex = value;
                    FixuptUser_ex(previousValue);
                }
            }
        }
        private tUser_ex _tUser_ex;

        #endregion

        #region Association Fixup
    
        private void FixuptUser_ex(tUser_ex previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.Base_Admin, this))
            {
                previousValue.Base_Admin = null;
            }
    
            if (tUser_ex != null)
            {
                tUser_ex.Base_Admin = this;
                if (UID != tUser_ex.UID)
                {
                    UID = tUser_ex.UID;
                }
            }
        }

        #endregion

    }
}
