//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace api.schoolbase.entities.DBBase
{
    
    public partial class _DBBase
    {
        public static @__api.schoolbase.entities.DBBase.Entity.Base_Group_Columns Base_Group = new @__api.schoolbase.entities.DBBase.Entity.Base_Group_Columns();
    }
    namespace @__api.schoolbase.entities.DBBase.Entity
    {
        public class Base_Group_Columns : MyLib.DbAccess.SQL.IQueryTable
        {
            private const string ___TABLE_NAME = "Base_Group";
            private string ___aliasName;
            public Base_Group_Columns(string aliasName) : base("DBBase") { this.___aliasName = aliasName; }
            public Base_Group_Columns() : base("DBBase") { this.___aliasName = ___TABLE_NAME; }
    
        #region Table Columns
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SERID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SERID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn SERID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SERID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SERID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _GCode = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".GCode"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn GCode
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _GCode;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".GCode"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _DepID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".DepID"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn DepID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _DepID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".DepID"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _UserType = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".UserType"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn UserType
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _UserType;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".UserType"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _GName = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".GName"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn GName
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _GName;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".GName"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _GDes = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".GDes"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn GDes
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _GDes;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".GDes"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _GMgr = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".GMgr"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn GMgr
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _GMgr;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".GMgr"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _GMgrName = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".GMgrName"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn GMgrName
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _GMgrName;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".GMgrName"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _GDate = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".GDate"), DbType.DateTime);
            public MyLib.DbAccess.SQL.QueryColumn GDate
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _GDate;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".GDate"), DbType.DateTime);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _IsOpen = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".IsOpen"), DbType.Byte);
            public MyLib.DbAccess.SQL.QueryColumn IsOpen
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _IsOpen;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".IsOpen"), DbType.Byte);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _IsRole = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".IsRole"), DbType.Boolean);
            public MyLib.DbAccess.SQL.QueryColumn IsRole
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _IsRole;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".IsRole"), DbType.Boolean);
                }
            }

        #endregion

                
            public override string ___GetTableName() { return ___TABLE_NAME; }
    		public override string ___GetAliasName() { return ___aliasName ?? ___TABLE_NAME; }
    		        public override IEnumerable<MyLib.DbAccess.SQL.QueryColumn> ___GetAutoIncrementColumn() { return new MyLib.DbAccess.SQL.QueryColumn[]{_SERID}; }
    				        public override MyLib.DbAccess.SQL.QueryColumn ___GetIdentityColumn() { return _SERID; }
            		public @__api.schoolbase.entities.DBBase.Entity.Base_Group_Columns @__Alias(string aliasName) { return new @__api.schoolbase.entities.DBBase.Entity.Base_Group_Columns(aliasName); }
        }
    }
    [System.Serializable]
    public partial class Base_Group
    {
        #region Property
    
        public virtual long SERID
        {
            get;
            set;
        }
    
        public virtual string GCode
        {
            get;
            set;
        }
    
        public virtual string DepID
        {
            get;
            set;
        }
    
        public virtual long UserType
        {
            get;
            set;
        }
    
        public virtual string GName
        {
            get;
            set;
        }
    
        public virtual string GDes
        {
            get;
            set;
        }
    
        public virtual Nullable<long> GMgr
        {
            get;
            set;
        }
    
        public virtual string GMgrName
        {
            get;
            set;
        }
    
        public virtual System.DateTime GDate
        {
            get { return _gDate; }
            set { 
    			if (value.Kind == DateTimeKind.Unspecified) {
    			_gDate = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_gDate = value;
    			}
    			}
        }
        private System.DateTime _gDate;
    
        public virtual byte IsOpen
        {
            get;
            set;
        }
    
        public virtual bool IsRole
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<Base_GroupPlug> Base_GroupPlug
        {
            get
            {
                if (_base_GroupPlug == null)
                {
                    var newCollection = new MyLib.DAO.FixupCollection<Base_GroupPlug>();
                    newCollection.CollectionChanged += FixupBase_GroupPlug;
                    _base_GroupPlug = newCollection;
                }
                return _base_GroupPlug;
            }
            set
            {
                if (!ReferenceEquals(_base_GroupPlug, value))
                {
                    var previousValue = _base_GroupPlug as MyLib.DAO.FixupCollection<Base_GroupPlug>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupBase_GroupPlug;
                    }
                    _base_GroupPlug = value;
                    var newValue = value as MyLib.DAO.FixupCollection<Base_GroupPlug>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupBase_GroupPlug;
                    }
                }
            }
        }
        private ICollection<Base_GroupPlug> _base_GroupPlug;
    
        public virtual ICollection<Base_GroupUser> Base_GroupUser
        {
            get
            {
                if (_base_GroupUser == null)
                {
                    var newCollection = new MyLib.DAO.FixupCollection<Base_GroupUser>();
                    newCollection.CollectionChanged += FixupBase_GroupUser;
                    _base_GroupUser = newCollection;
                }
                return _base_GroupUser;
            }
            set
            {
                if (!ReferenceEquals(_base_GroupUser, value))
                {
                    var previousValue = _base_GroupUser as MyLib.DAO.FixupCollection<Base_GroupUser>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupBase_GroupUser;
                    }
                    _base_GroupUser = value;
                    var newValue = value as MyLib.DAO.FixupCollection<Base_GroupUser>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupBase_GroupUser;
                    }
                }
            }
        }
        private ICollection<Base_GroupUser> _base_GroupUser;
    
        public virtual ICollection<Base_MyPlug> Base_MyPlug
        {
            get
            {
                if (_base_MyPlug == null)
                {
                    var newCollection = new MyLib.DAO.FixupCollection<Base_MyPlug>();
                    newCollection.CollectionChanged += FixupBase_MyPlug;
                    _base_MyPlug = newCollection;
                }
                return _base_MyPlug;
            }
            set
            {
                if (!ReferenceEquals(_base_MyPlug, value))
                {
                    var previousValue = _base_MyPlug as MyLib.DAO.FixupCollection<Base_MyPlug>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupBase_MyPlug;
                    }
                    _base_MyPlug = value;
                    var newValue = value as MyLib.DAO.FixupCollection<Base_MyPlug>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupBase_MyPlug;
                    }
                }
            }
        }
        private ICollection<Base_MyPlug> _base_MyPlug;

        #endregion

        #region Association Fixup
    
        private void FixupBase_GroupPlug(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Base_GroupPlug item in e.NewItems)
                {
                    item.Base_Group = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Base_GroupPlug item in e.OldItems)
                {
                    if (ReferenceEquals(item.Base_Group, this))
                    {
                        item.Base_Group = null;
                    }
                }
            }
        }
    
        private void FixupBase_GroupUser(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Base_GroupUser item in e.NewItems)
                {
                    item.Base_Group = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Base_GroupUser item in e.OldItems)
                {
                    if (ReferenceEquals(item.Base_Group, this))
                    {
                        item.Base_Group = null;
                    }
                }
            }
        }
    
        private void FixupBase_MyPlug(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Base_MyPlug item in e.NewItems)
                {
                    item.Base_Group = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Base_MyPlug item in e.OldItems)
                {
                    if (ReferenceEquals(item.Base_Group, this))
                    {
                        item.Base_Group = null;
                    }
                }
            }
        }

        #endregion

    }
}
