//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace api.schoolbase.entities.DBBase
{
    
    public partial class _DBBase
    {
        public static @__api.schoolbase.entities.DBBase.Entity.Base_VAdmin_Columns Base_VAdmin = new @__api.schoolbase.entities.DBBase.Entity.Base_VAdmin_Columns();
    }
    namespace @__api.schoolbase.entities.DBBase.Entity
    {
        public class Base_VAdmin_Columns : MyLib.DbAccess.SQL.IQueryTable
        {
            private const string ___TABLE_NAME = "Base_VAdmin";
            private string ___aliasName;
            public Base_VAdmin_Columns(string aliasName) : base("DBBase") { this.___aliasName = aliasName; }
            public Base_VAdmin_Columns() : base("DBBase") { this.___aliasName = ___TABLE_NAME; }
    
        #region Table Columns
    
    		private static MyLib.DbAccess.SQL.QueryColumn _UID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".UID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn UID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _UID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".UID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _Accout = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".Accout"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn Accout
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _Accout;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".Accout"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _UserName = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".UserName"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn UserName
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _UserName;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".UserName"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _UserType = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".UserType"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn UserType
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _UserType;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".UserType"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _DefaultApp = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".DefaultApp"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn DefaultApp
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _DefaultApp;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".DefaultApp"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _DepID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".DepID"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn DepID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _DepID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".DepID"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _Switch = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".Switch"), DbType.Byte);
            public MyLib.DbAccess.SQL.QueryColumn Switch
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _Switch;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".Switch"), DbType.Byte);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _Tel = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".Tel"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn Tel
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _Tel;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".Tel"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _Email = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".Email"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn Email
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _Email;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".Email"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _Addr = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".Addr"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn Addr
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _Addr;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".Addr"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _DTime = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".DTime"), DbType.DateTime);
            public MyLib.DbAccess.SQL.QueryColumn DTime
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _DTime;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".DTime"), DbType.DateTime);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _IP = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".IP"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn IP
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _IP;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".IP"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _DepName = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".DepName"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn DepName
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _DepName;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".DepName"), DbType.String);
                }
            }

        #endregion

                
            public override string ___GetTableName() { return ___TABLE_NAME; }
    		public override string ___GetAliasName() { return ___aliasName ?? ___TABLE_NAME; }
    				        public override MyLib.DbAccess.SQL.QueryColumn ___GetIdentityColumn() { return _UID; }
            		public @__api.schoolbase.entities.DBBase.Entity.Base_VAdmin_Columns @__Alias(string aliasName) { return new @__api.schoolbase.entities.DBBase.Entity.Base_VAdmin_Columns(aliasName); }
        }
    }
    [System.Serializable]
    public partial class Base_VAdmin
    {
        #region Property
    
        public virtual long UID
        {
            get;
            set;
        }
    
        public virtual string Accout
        {
            get;
            set;
        }
    
        public virtual string UserName
        {
            get;
            set;
        }
    
        public virtual long UserType
        {
            get;
            set;
        }
    
        public virtual string DefaultApp
        {
            get;
            set;
        }
    
        public virtual string DepID
        {
            get;
            set;
        }
    
        public virtual byte Switch
        {
            get;
            set;
        }
    
        public virtual string Tel
        {
            get;
            set;
        }
    
        public virtual string Email
        {
            get;
            set;
        }
    
        public virtual string Addr
        {
            get;
            set;
        }
    
        public virtual System.DateTime DTime
        {
            get { return _dTime; }
            set { 
    			if (value.Kind == DateTimeKind.Unspecified) {
    			_dTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_dTime = value;
    			}
    			}
        }
        private System.DateTime _dTime;
    
        public virtual string IP
        {
            get;
            set;
        }
    
        public virtual string DepName
        {
            get;
            set;
        }

        #endregion

    }
}
