//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace api.schoolbase.entities.DBBase
{
    
    public partial class _DBBase
    {
        public static @__api.schoolbase.entities.DBBase.Entity.VGroup_Columns VGroup = new @__api.schoolbase.entities.DBBase.Entity.VGroup_Columns();
    }
    namespace @__api.schoolbase.entities.DBBase.Entity
    {
        public class VGroup_Columns : MyLib.DbAccess.SQL.IQueryTable
        {
            private const string ___TABLE_NAME = "VGroup";
            private string ___aliasName;
            public VGroup_Columns(string aliasName) : base("DBBase") { this.___aliasName = aliasName; }
            public VGroup_Columns() : base("DBBase") { this.___aliasName = ___TABLE_NAME; }
    
        #region Table Columns
    
    		private static MyLib.DbAccess.SQL.QueryColumn _SERID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".SERID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn SERID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _SERID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".SERID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _DepID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".DepID"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn DepID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _DepID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".DepID"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _DepName = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".DepName"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn DepName
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _DepName;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".DepName"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _NameEn = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".NameEn"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn NameEn
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _NameEn;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".NameEn"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _GCode = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".GCode"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn GCode
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _GCode;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".GCode"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _UserType = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".UserType"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn UserType
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _UserType;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".UserType"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _GName = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".GName"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn GName
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _GName;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".GName"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _GDes = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".GDes"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn GDes
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _GDes;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".GDes"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _GMgr = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".GMgr"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn GMgr
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _GMgr;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".GMgr"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _GMgrName = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".GMgrName"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn GMgrName
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _GMgrName;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".GMgrName"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _GDate = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".GDate"), DbType.DateTime);
            public MyLib.DbAccess.SQL.QueryColumn GDate
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _GDate;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".GDate"), DbType.DateTime);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _IsOpen = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".IsOpen"), DbType.Byte);
            public MyLib.DbAccess.SQL.QueryColumn IsOpen
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _IsOpen;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".IsOpen"), DbType.Byte);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _IsRole = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".IsRole"), DbType.Boolean);
            public MyLib.DbAccess.SQL.QueryColumn IsRole
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _IsRole;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".IsRole"), DbType.Boolean);
                }
            }

        #endregion

                
            public override string ___GetTableName() { return ___TABLE_NAME; }
    		public override string ___GetAliasName() { return ___aliasName ?? ___TABLE_NAME; }
    				        public override MyLib.DbAccess.SQL.QueryColumn ___GetIdentityColumn() { return _SERID; }
            		public @__api.schoolbase.entities.DBBase.Entity.VGroup_Columns @__Alias(string aliasName) { return new @__api.schoolbase.entities.DBBase.Entity.VGroup_Columns(aliasName); }
        }
    }
    [System.Serializable]
    public partial class VGroup
    {
        #region Property
    
        public virtual long SERID
        {
            get;
            set;
        }
    
        public virtual string DepID
        {
            get;
            set;
        }
    
        public virtual string DepName
        {
            get;
            set;
        }
    
        public virtual string NameEn
        {
            get;
            set;
        }
    
        public virtual string GCode
        {
            get;
            set;
        }
    
        public virtual long UserType
        {
            get;
            set;
        }
    
        public virtual string GName
        {
            get;
            set;
        }
    
        public virtual string GDes
        {
            get;
            set;
        }
    
        public virtual Nullable<long> GMgr
        {
            get;
            set;
        }
    
        public virtual string GMgrName
        {
            get;
            set;
        }
    
        public virtual System.DateTime GDate
        {
            get { return _gDate; }
            set { 
    			if (value.Kind == DateTimeKind.Unspecified) {
    			_gDate = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_gDate = value;
    			}
    			}
        }
        private System.DateTime _gDate;
    
        public virtual byte IsOpen
        {
            get;
            set;
        }
    
        public virtual bool IsRole
        {
            get;
            set;
        }

        #endregion

    }
}
