//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace api.schoolbase.entities.DBBase
{
    
    public partial class _DBBase
    {
        public static @__api.schoolbase.entities.DBBase.Entity.VUser_Columns VUser = new @__api.schoolbase.entities.DBBase.Entity.VUser_Columns();
    }
    namespace @__api.schoolbase.entities.DBBase.Entity
    {
        public class VUser_Columns : MyLib.DbAccess.SQL.IQueryTable
        {
            private const string ___TABLE_NAME = "VUser";
            private string ___aliasName;
            public VUser_Columns(string aliasName) : base("DBBase") { this.___aliasName = aliasName; }
            public VUser_Columns() : base("DBBase") { this.___aliasName = ___TABLE_NAME; }
    
        #region Table Columns
    
    		private static MyLib.DbAccess.SQL.QueryColumn _UID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".UID"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn UID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _UID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".UID"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _DepID = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".DepID"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn DepID
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _DepID;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".DepID"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _UserType = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".UserType"), DbType.Int64);
            public MyLib.DbAccess.SQL.QueryColumn UserType
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _UserType;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".UserType"), DbType.Int64);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _Accout = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".Accout"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn Accout
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _Accout;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".Accout"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _Switch = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".Switch"), DbType.Byte);
            public MyLib.DbAccess.SQL.QueryColumn Switch
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _Switch;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".Switch"), DbType.Byte);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _Email = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".Email"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn Email
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _Email;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".Email"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _Photo = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".Photo"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn Photo
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _Photo;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".Photo"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _DefaultApp = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".DefaultApp"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn DefaultApp
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _DefaultApp;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".DefaultApp"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _UserID2 = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".UserID2"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn UserID2
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _UserID2;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".UserID2"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _UserID3 = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".UserID3"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn UserID3
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _UserID3;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".UserID3"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _pwd = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".pwd"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn pwd
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _pwd;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".pwd"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _UserName = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".UserName"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn UserName
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _UserName;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".UserName"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _Personmsg = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".Personmsg"), DbType.String);
            public MyLib.DbAccess.SQL.QueryColumn Personmsg
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _Personmsg;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".Personmsg"), DbType.String);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _Logintime = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".Logintime"), DbType.DateTime);
            public MyLib.DbAccess.SQL.QueryColumn Logintime
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _Logintime;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".Logintime"), DbType.DateTime);
                }
            }
    
    		private static MyLib.DbAccess.SQL.QueryColumn _Logouttime = new MyLib.DbAccess.SQL.QueryColumn((___TABLE_NAME + ".Logouttime"), DbType.DateTime);
            public MyLib.DbAccess.SQL.QueryColumn Logouttime
            {
                get
                {
                    if ((this.___aliasName == ___TABLE_NAME)) return _Logouttime;
                    else return new MyLib.DbAccess.SQL.QueryColumn((this.___aliasName + ".Logouttime"), DbType.DateTime);
                }
            }

        #endregion

                
            public override string ___GetTableName() { return ___TABLE_NAME; }
    		public override string ___GetAliasName() { return ___aliasName ?? ___TABLE_NAME; }
    				        public override MyLib.DbAccess.SQL.QueryColumn ___GetIdentityColumn() { return _UID; }
            		public @__api.schoolbase.entities.DBBase.Entity.VUser_Columns @__Alias(string aliasName) { return new @__api.schoolbase.entities.DBBase.Entity.VUser_Columns(aliasName); }
        }
    }
    [System.Serializable]
    public partial class VUser
    {
        #region Property
    
        public virtual long UID
        {
            get;
            set;
        }
    
        public virtual string DepID
        {
            get;
            set;
        }
    
        public virtual long UserType
        {
            get;
            set;
        }
    
        public virtual string Accout
        {
            get;
            set;
        }
    
        public virtual byte Switch
        {
            get;
            set;
        }
    
        public virtual string Email
        {
            get;
            set;
        }
    
        public virtual string Photo
        {
            get;
            set;
        }
    
        public virtual string DefaultApp
        {
            get;
            set;
        }
    
        public virtual string UserID2
        {
            get;
            set;
        }
    
        public virtual string UserID3
        {
            get;
            set;
        }
    
        public virtual string pwd
        {
            get;
            set;
        }
    
        public virtual string UserName
        {
            get;
            set;
        }
    
        public virtual string Personmsg
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Logintime
        {
            get { return _logintime; }
            set { 
    			if (value != null){
    				if (value.Value.Kind == DateTimeKind.Unspecified) {
    					_logintime = DateTime.SpecifyKind(value.Value, DateTimeKind.Utc);
    				} else {
    					_logintime = value;
    				}
    			}
    			else 		_logintime = value; 
    	}
        }
        private Nullable<System.DateTime> _logintime;
    
        public virtual Nullable<System.DateTime> Logouttime
        {
            get { return _logouttime; }
            set { 
    			if (value != null){
    				if (value.Value.Kind == DateTimeKind.Unspecified) {
    					_logouttime = DateTime.SpecifyKind(value.Value, DateTimeKind.Utc);
    				} else {
    					_logouttime = value;
    				}
    			}
    			else 		_logouttime = value; 
    	}
        }
        private Nullable<System.DateTime> _logouttime;

        #endregion

    }
}
