//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.schoolbase.SchoolBaseServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SchoolBaseServer.SchoolBaseSoap")]
    public interface SchoolBaseSoap {
        
        // CODEGEN: 参数“zipFile”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserModifyHead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        api.schoolbase.SchoolBaseServer.UserModifyHeadResponse UserModifyHead(api.schoolbase.SchoolBaseServer.UserModifyHeadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserModifyHead", ReplyAction="*")]
        System.Threading.Tasks.Task<api.schoolbase.SchoolBaseServer.UserModifyHeadResponse> UserModifyHeadAsync(api.schoolbase.SchoolBaseServer.UserModifyHeadRequest request);
        
        // CODEGEN: 参数“zipFile”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadZipFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        api.schoolbase.SchoolBaseServer.UploadZipFileResponse UploadZipFile(api.schoolbase.SchoolBaseServer.UploadZipFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadZipFile", ReplyAction="*")]
        System.Threading.Tasks.Task<api.schoolbase.SchoolBaseServer.UploadZipFileResponse> UploadZipFileAsync(api.schoolbase.SchoolBaseServer.UploadZipFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserModifyHead", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserModifyHeadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string filetype;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] zipFile;
        
        public UserModifyHeadRequest() {
        }
        
        public UserModifyHeadRequest(string token, string filetype, byte[] zipFile) {
            this.token = token;
            this.filetype = filetype;
            this.zipFile = zipFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserModifyHeadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserModifyHeadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int UserModifyHeadResult;
        
        public UserModifyHeadResponse() {
        }
        
        public UserModifyHeadResponse(int UserModifyHeadResult) {
            this.UserModifyHeadResult = UserModifyHeadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadZipFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadZipFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] zipFile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string fname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ftype;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string did;
        
        public UploadZipFileRequest() {
        }
        
        public UploadZipFileRequest(string userId, byte[] zipFile, string fname, string ftype, string did) {
            this.userId = userId;
            this.zipFile = zipFile;
            this.fname = fname;
            this.ftype = ftype;
            this.did = did;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadZipFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadZipFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int UploadZipFileResult;
        
        public UploadZipFileResponse() {
        }
        
        public UploadZipFileResponse(int UploadZipFileResult) {
            this.UploadZipFileResult = UploadZipFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SchoolBaseSoapChannel : api.schoolbase.SchoolBaseServer.SchoolBaseSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SchoolBaseSoapClient : System.ServiceModel.ClientBase<api.schoolbase.SchoolBaseServer.SchoolBaseSoap>, api.schoolbase.SchoolBaseServer.SchoolBaseSoap {
        
        public SchoolBaseSoapClient() {
        }
        
        public SchoolBaseSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SchoolBaseSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchoolBaseSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchoolBaseSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        api.schoolbase.SchoolBaseServer.UserModifyHeadResponse api.schoolbase.SchoolBaseServer.SchoolBaseSoap.UserModifyHead(api.schoolbase.SchoolBaseServer.UserModifyHeadRequest request) {
            return base.Channel.UserModifyHead(request);
        }
        
        public int UserModifyHead(string token, string filetype, byte[] zipFile) {
            api.schoolbase.SchoolBaseServer.UserModifyHeadRequest inValue = new api.schoolbase.SchoolBaseServer.UserModifyHeadRequest();
            inValue.token = token;
            inValue.filetype = filetype;
            inValue.zipFile = zipFile;
            api.schoolbase.SchoolBaseServer.UserModifyHeadResponse retVal = ((api.schoolbase.SchoolBaseServer.SchoolBaseSoap)(this)).UserModifyHead(inValue);
            return retVal.UserModifyHeadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<api.schoolbase.SchoolBaseServer.UserModifyHeadResponse> api.schoolbase.SchoolBaseServer.SchoolBaseSoap.UserModifyHeadAsync(api.schoolbase.SchoolBaseServer.UserModifyHeadRequest request) {
            return base.Channel.UserModifyHeadAsync(request);
        }
        
        public System.Threading.Tasks.Task<api.schoolbase.SchoolBaseServer.UserModifyHeadResponse> UserModifyHeadAsync(string token, string filetype, byte[] zipFile) {
            api.schoolbase.SchoolBaseServer.UserModifyHeadRequest inValue = new api.schoolbase.SchoolBaseServer.UserModifyHeadRequest();
            inValue.token = token;
            inValue.filetype = filetype;
            inValue.zipFile = zipFile;
            return ((api.schoolbase.SchoolBaseServer.SchoolBaseSoap)(this)).UserModifyHeadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        api.schoolbase.SchoolBaseServer.UploadZipFileResponse api.schoolbase.SchoolBaseServer.SchoolBaseSoap.UploadZipFile(api.schoolbase.SchoolBaseServer.UploadZipFileRequest request) {
            return base.Channel.UploadZipFile(request);
        }
        
        public int UploadZipFile(string userId, byte[] zipFile, string fname, string ftype, string did) {
            api.schoolbase.SchoolBaseServer.UploadZipFileRequest inValue = new api.schoolbase.SchoolBaseServer.UploadZipFileRequest();
            inValue.userId = userId;
            inValue.zipFile = zipFile;
            inValue.fname = fname;
            inValue.ftype = ftype;
            inValue.did = did;
            api.schoolbase.SchoolBaseServer.UploadZipFileResponse retVal = ((api.schoolbase.SchoolBaseServer.SchoolBaseSoap)(this)).UploadZipFile(inValue);
            return retVal.UploadZipFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<api.schoolbase.SchoolBaseServer.UploadZipFileResponse> api.schoolbase.SchoolBaseServer.SchoolBaseSoap.UploadZipFileAsync(api.schoolbase.SchoolBaseServer.UploadZipFileRequest request) {
            return base.Channel.UploadZipFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<api.schoolbase.SchoolBaseServer.UploadZipFileResponse> UploadZipFileAsync(string userId, byte[] zipFile, string fname, string ftype, string did) {
            api.schoolbase.SchoolBaseServer.UploadZipFileRequest inValue = new api.schoolbase.SchoolBaseServer.UploadZipFileRequest();
            inValue.userId = userId;
            inValue.zipFile = zipFile;
            inValue.fname = fname;
            inValue.ftype = ftype;
            inValue.did = did;
            return ((api.schoolbase.SchoolBaseServer.SchoolBaseSoap)(this)).UploadZipFileAsync(inValue);
        }
    }
}
